### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by sega-yarkin** [bakkerthehacker/bramqp#44]
I've error (`Invalid Date`) with timestamp field from RabbitMQ. It looks like [here](https://github.com/bakkerthehacker/bramqp/blob/master/lib/frameParser.js#L178) should be a division instead multiplication (at least for me it helps).

**Comment by bakkerthehacker** [comment]
That should definitely be a multiplication.  The [javascript date contructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) takes the number of milliseconds as its argument.  

>value
    Integer value representing the number of milliseconds since 1 January 1970 00:00:00 UTC (Unix Epoch).

And RabbitMQ uses seconds for its timestamps.  

> Time stamps are held in the 64-bit POSIX time_t format with an accuracy of one second. 

I am not sure what number RabbitMQ is passing as a date here as any integer should be valid.  Could you post some code to reproduce this?

**Comment by sega-yarkin** [comment]
I'm using [RabbitMQ Event Exchange plugin](https://github.com/rabbitmq/rabbitmq-event-exchange), it sends timestamp field in microseconds, maybe it's wrong behavior, but I lose original value. Maybe return original value if parsing date failed?

**Comment by bakkerthehacker** [comment]
I can look into this plugin, but I do not think that the problem or the solution is in bramqp.  If this plugin is sending timestamps that are not standard, it would make more sense that it is an issue with the plugin rather than the bramqp library.  The solution you proposed is not part of the standard and it is impossible to determine which time format to serialize timestamps when they are sent to the server.

Additionally, other libraries, such as node-amqp use the same multiplication that is used in bramqp, as seen [here](https://github.com/postwait/node-amqp/blob/f64704d3727266230901598e2daf0fa780766feb/lib/parser.js#L220).

**Comment by sega-yarkin** [comment]
Okay, thanks for your answer! The last question: can I get the original field value after it was parsed?

**Comment by bakkerthehacker** [comment]
I dont think it is currently possible to extract the raw value without directly modifying the bramqp library.

**Comment by vitaly-krugl** [comment]
See https://github.com/rabbitmq/rabbitmq-event-exchange/issues/8
